# Use `DataFrame.iloc[..., ...]` to selet values by their (entry) position

In [54]:
import pandas as pd
data = pd.read_csv('data/gapminder_gdp_europe.csv', 
                  index_col='country'
                  )
data

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.003910,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
Austria,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.422300,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700
Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080
Bosnia and Herzegovina,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803
Bulgaria,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,7696.777725,10680.792820
Croatia,3119.236520,4338.231617,5477.890018,6960.297861,9164.090127,11305.385170,13221.821840,13822.583940,8447.794873,9875.604515,11628.388950,14619.222720
Czech Republic,6876.140250,8256.343918,10136.867130,11399.444890,13108.453600,14800.160620,15377.228550,16310.443400,14297.021220,16048.514240,17596.210220,22833.308510
Denmark,9692.385245,11099.659350,13583.313510,15937.211230,18866.207210,20422.901500,21688.040480,25116.175810,26406.739850,29804.345670,32166.500060,35278.418740
Finland,6424.519071,7545.415386,9371.842561,10921.636260,14358.875900,15605.422830,18533.157610,21141.012230,20647.164990,23723.950200,28204.590570,33207.084400
France,7029.809327,8662.834898,10560.485530,12999.917660,16107.191710,18292.635140,20293.897460,22066.442140,24703.796150,25889.784870,28926.032340,30470.016700
Germany,7144.114393,10187.826650,12902.462910,14745.625610,18016.180270,20512.921230,22031.532740,24639.185660,26505.303170,27788.884160,30035.801980,32170.374420
Greece,3530.690067,4916.299889,6017.190733,8513.097016,12724.829570,14195.524280,15268.420890,16120.528390,17541.496340,18747.698140,22514.254800,27538.411880
Hungary,5263.673816,6040.180011,7550.359877,9326.644670,10168.656110,11674.837370,12545.990660,12986.479980,10535.628550,11712.776800,14843.935560,18008.944440
Iceland,7267.688428,9244.001412,10350.159060,13319.895680,15798.063620,19654.962470,23269.607500,26923.206280,25144.392010,28061.099660,31163.201960,36180.789190
Ireland,5210.280328,5599.077872,6631.597314,7655.568963,9530.772896,11150.981130,12618.321410,13872.866520,17558.815550,24521.947130,34077.049390,40675.996350
Italy,4931.404155,6248.656232,8243.582340,10022.401310,12269.273780,14255.984750,16537.483500,19207.234820,22013.644860,24675.024460,27968.098170,28569.719700
Montenegro,2647.585601,3682.259903,4649.593785,5907.850937,7778.414017,9595.929905,11222.587620,11732.510170,7003.339037,6465.613349,6557.194282,9253.896111
Netherlands,8941.571858,11276.193440,12790.849560,15363.251360,18794.745670,21209.059200,21399.460460,23651.323610,26790.949610,30246.130630,33724.757780,36797.933320
Norway,10095.421720,11653.973040,13450.401510,16361.876470,18965.055510,23311.349390,26298.635310,31540.974800,33965.661150,41283.164330,44683.975250,49357.190170
Poland,4029.329699,4734.253019,5338.752143,6557.152776,8006.506993,9508.141454,8451.531004,9082.351172,7738.881247,10159.583680,12002.239080,15389.924680
Portugal,3068.319867,3774.571743,4727.954889,6361.517993,9022.247417,10172.485720,11753.842910,13039.308760,16207.266630,17641.031560,19970.907870,20509.647770
Romania,3144.613186,3943.370225,4734.997586,6470.866545,8011.414402,9356.397240,9605.314053,9696.273295,6598.409903,7346.547557,7885.360081,10808.475610
Serbia,3581.459448,4981.090891,6289.629157,7991.707066,10522.067490,12980.669560,15181.092700,15870.878510,9325.068238,7914.320304,7236.075251,9786.534714
Slovak Republic,5074.659104,6093.262980,7481.107598,8412.902397,9674.167626,10922.664040,11348.545850,12037.267580,9498.467723,12126.230650,13638.778370,18678.314350
Slovenia,4215.041741,5862.276629,7402.303395,9405.489397,12383.486200,15277.030170,17866.721750,18678.534920,14214.716810,17161.107350,20660.019360,25768.257590
Spain,3834.034742,4564.802410,5693.843879,7993.512294,10638.751310,13236.921170,13926.169970,15764.983130,18603.064520,20445.298960,24835.471660,28821.063700
Sweden,8527.844662,9911.878226,12329.441920,15258.296970,17832.024640,18855.725210,20667.381250,23586.929270,23880.016830,25266.594990,29341.630930,33859.748350
Switzerland,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,30281.704590,31871.530300,32135.323010,34480.957710,37506.419070
Turkey,1969.100980,2218.754257,2322.869908,2826.356387,3450.696380,4269.122326,4241.356344,5089.043686,5678.348271,6601.429915,6508.085718,8458.276384
United Kingdom,9979.508487,11283.177950,12477.177070,14142.850890,15895.116410,17428.748460,18232.424520,21664.787670,22705.092540,26074.531360,29478.999190,33203.261280

In [55]:
data.columns

Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'],
      dtype='object')

In [57]:
data.index

Index(['Albania', 'Austria', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria',
       'Croatia', 'Czech Republic', 'Denmark', 'Finland', 'France', 'Germany',
       'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy', 'Montenegro',
       'Netherlands', 'Norway', 'Poland', 'Portugal', 'Romania', 'Serbia',
       'Slovak Republic', 'Slovenia', 'Spain', 'Sweden', 'Switzerland',
       'Turkey', 'United Kingdom'],
      dtype='object', name='country')

In [46]:
data.iloc[0,0]

'Albania'

In [50]:
data.T.loc[:,  0:3]

                      0        1        2                       3
country         Albania  Austria  Belgium  Bosnia and Herzegovina
gdpPercap_1952  1601.06  6137.08  8343.11                 973.533
gdpPercap_1957  1942.28   8842.6  9714.96                 1353.99
gdpPercap_1962  2312.89  10750.7  10991.2                 1709.68
gdpPercap_1967   2760.2  12834.6    13149                 2172.35
gdpPercap_1972  3313.42  16661.6  16672.1                 2860.17
gdpPercap_1977     3533  19749.4    19118                 3528.48
gdpPercap_1982  3630.88  21597.1  20979.8                 4126.61
gdpPercap_1987  3738.93  23687.8  22525.6                 4314.11
gdpPercap_1992  2497.44    27042  25575.6                 2546.78
gdpPercap_1997  3193.05  29095.9  27561.2                 4766.36
gdpPercap_2002  4604.21  32417.6  30485.9                 6018.98
gdpPercap_2007  5937.03  36126.5  33692.6                  7446.3

In [47]:
data.iloc[:, 0:3]

                   country  gdpPercap_1952  gdpPercap_1957
0                  Albania     1601.056136     1942.284244
1                  Austria     6137.076492     8842.598030
2                  Belgium     8343.105127     9714.960623
3   Bosnia and Herzegovina      973.533195     1353.989176
4                 Bulgaria     2444.286648     3008.670727
5                  Croatia     3119.236520     4338.231617
6           Czech Republic     6876.140250     8256.343918
7                  Denmark     9692.385245    11099.659350
8                  Finland     6424.519071     7545.415386
9                   France     7029.809327     8662.834898
10                 Germany     7144.114393    10187.826650
11                  Greece     3530.690067     4916.299889
12                 Hungary     5263.673816     6040.180011
13                 Iceland     7267.688428     9244.001412
14                 Ireland     5210.280328     5599.077872
15                   Italy     4931.404155     6248.656232
16              Montenegro     2647.585601     3682.259903
17             Netherlands     8941.571858    11276.193440
18                  Norway    10095.421720    11653.973040
19                  Poland     4029.329699     4734.253019
20                Portugal     3068.319867     3774.571743
21                 Romania     3144.613186     3943.370225
22                  Serbia     3581.459448     4981.090891
23         Slovak Republic     5074.659104     6093.262980
24                Slovenia     4215.041741     5862.276629
25                   Spain     3834.034742     4564.802410
26                  Sweden     8527.844662     9911.878226
27             Switzerland    14734.232750    17909.489730
28                  Turkey     1969.100980     2218.754257
29          United Kingdom     9979.508487    11283.177950

In [8]:
data.loc['Albania','gdpPercap_1952']

1601.056136

In [34]:
#display(data.loc['Albania', :].to_frame('Albania')), 
data.loc[:,['gdpPercap_1952','gdpPercap_1957']]

                        gdpPercap_1952  gdpPercap_1957
country
Albania                    1601.056136     1942.284244
Austria                    6137.076492     8842.598030
Belgium                    8343.105127     9714.960623
Bosnia and Herzegovina      973.533195     1353.989176
Bulgaria                   2444.286648     3008.670727
Croatia                    3119.236520     4338.231617
Czech Republic             6876.140250     8256.343918
Denmark                    9692.385245    11099.659350
Finland                    6424.519071     7545.415386
France                     7029.809327     8662.834898
Germany                    7144.114393    10187.826650
Greece                     3530.690067     4916.299889
Hungary                    5263.673816     6040.180011
Iceland                    7267.688428     9244.001412
Ireland                    5210.280328     5599.077872
Italy                      4931.404155     6248.656232
Montenegro                 2647.585601     3682.259903
Netherlands                8941.571858    11276.193440
Norway                    10095.421720    11653.973040
Poland                     4029.329699     4734.253019
Portugal                   3068.319867     3774.571743
Romania                    3144.613186     3943.370225
Serbia                     3581.459448     4981.090891
Slovak Republic            5074.659104     6093.262980
Slovenia                   4215.041741     5862.276629
Spain                      3834.034742     4564.802410
Sweden                     8527.844662     9911.878226
Switzerland               14734.232750    17909.489730
Turkey                     1969.100980     2218.754257
United Kingdom             9979.508487    11283.177950

In [43]:
data.loc[:,'gdpPercap_1952':'gdpPercap_1962']

                        gdpPercap_1952  gdpPercap_1957  gdpPercap_1962
country
Albania                    1601.056136     1942.284244     2312.888958
Austria                    6137.076492     8842.598030    10750.721110
Belgium                    8343.105127     9714.960623    10991.206760
Bosnia and Herzegovina      973.533195     1353.989176     1709.683679
Bulgaria                   2444.286648     3008.670727     4254.337839
Croatia                    3119.236520     4338.231617     5477.890018
Czech Republic             6876.140250     8256.343918    10136.867130
Denmark                    9692.385245    11099.659350    13583.313510
Finland                    6424.519071     7545.415386     9371.842561
France                     7029.809327     8662.834898    10560.485530
Germany                    7144.114393    10187.826650    12902.462910
Greece                     3530.690067     4916.299889     6017.190733
Hungary                    5263.673816     6040.180011     7550.359877
Iceland                    7267.688428     9244.001412    10350.159060
Ireland                    5210.280328     5599.077872     6631.597314
Italy                      4931.404155     6248.656232     8243.582340
Montenegro                 2647.585601     3682.259903     4649.593785
Netherlands                8941.571858    11276.193440    12790.849560
Norway                    10095.421720    11653.973040    13450.401510
Poland                     4029.329699     4734.253019     5338.752143
Portugal                   3068.319867     3774.571743     4727.954889
Romania                    3144.613186     3943.370225     4734.997586
Serbia                     3581.459448     4981.090891     6289.629157
Slovak Republic            5074.659104     6093.262980     7481.107598
Slovenia                   4215.041741     5862.276629     7402.303395
Spain                      3834.034742     4564.802410     5693.843879
Sweden                     8527.844662     9911.878226    12329.441920
Switzerland               14734.232750    17909.489730    20431.092700
Turkey                     1969.100980     2218.754257     2322.869908
United Kingdom             9979.508487    11283.177950    12477.177070

# `iloc` has different semantics than `loc` when it comes to slicing

In [40]:
data.iloc[:,0:3]

                        gdpPercap_1952  gdpPercap_1957  gdpPercap_1962
country
Albania                    1601.056136     1942.284244     2312.888958
Austria                    6137.076492     8842.598030    10750.721110
Belgium                    8343.105127     9714.960623    10991.206760
Bosnia and Herzegovina      973.533195     1353.989176     1709.683679
Bulgaria                   2444.286648     3008.670727     4254.337839
Croatia                    3119.236520     4338.231617     5477.890018
Czech Republic             6876.140250     8256.343918    10136.867130
Denmark                    9692.385245    11099.659350    13583.313510
Finland                    6424.519071     7545.415386     9371.842561
France                     7029.809327     8662.834898    10560.485530
Germany                    7144.114393    10187.826650    12902.462910
Greece                     3530.690067     4916.299889     6017.190733
Hungary                    5263.673816     6040.180011     7550.359877
Iceland                    7267.688428     9244.001412    10350.159060
Ireland                    5210.280328     5599.077872     6631.597314
Italy                      4931.404155     6248.656232     8243.582340
Montenegro                 2647.585601     3682.259903     4649.593785
Netherlands                8941.571858    11276.193440    12790.849560
Norway                    10095.421720    11653.973040    13450.401510
Poland                     4029.329699     4734.253019     5338.752143
Portugal                   3068.319867     3774.571743     4727.954889
Romania                    3144.613186     3943.370225     4734.997586
Serbia                     3581.459448     4981.090891     6289.629157
Slovak Republic            5074.659104     6093.262980     7481.107598
Slovenia                   4215.041741     5862.276629     7402.303395
Spain                      3834.034742     4564.802410     5693.843879
Sweden                     8527.844662     9911.878226    12329.441920
Switzerland               14734.232750    17909.489730    20431.092700
Turkey                     1969.100980     2218.754257     2322.869908
United Kingdom             9979.508487    11283.177950    12477.177070

In [14]:
data.loc['Albania'].to_frame('Albania')

                    Albania
gdpPercap_1952  1601.056136
gdpPercap_1957  1942.284244
gdpPercap_1962  2312.888958
gdpPercap_1967  2760.196931
gdpPercap_1972  3313.422188
gdpPercap_1977  3533.003910
gdpPercap_1982  3630.880722
gdpPercap_1987  3738.932735
gdpPercap_1992  2497.437901
gdpPercap_1997  3193.054604
gdpPercap_2002  4604.211737
gdpPercap_2007  5937.029526

In [15]:
data.loc[:, 'gdpPercap_1952'].to_frame('gdpPercap_1952')

                        gdpPercap_1952
country
Albania                    1601.056136
Austria                    6137.076492
Belgium                    8343.105127
Bosnia and Herzegovina      973.533195
Bulgaria                   2444.286648
Croatia                    3119.236520
Czech Republic             6876.140250
Denmark                    9692.385245
Finland                    6424.519071
France                     7029.809327
Germany                    7144.114393
Greece                     3530.690067
Hungary                    5263.673816
Iceland                    7267.688428
Ireland                    5210.280328
Italy                      4931.404155
Montenegro                 2647.585601
Netherlands                8941.571858
Norway                    10095.421720
Poland                     4029.329699
Portugal                   3068.319867
Romania                    3144.613186
Serbia                     3581.459448
Slovak Republic            5074.659104
Slovenia                   4215.041741
Spain                      3834.034742
Sweden                     8527.844662
Switzerland               14734.232750
Turkey                     1969.100980
United Kingdom             9979.508487

In [16]:
data['gdpPercap_1952'].to_frame('gdpPercap_1952')

                        gdpPercap_1952
country
Albania                    1601.056136
Austria                    6137.076492
Belgium                    8343.105127
Bosnia and Herzegovina      973.533195
Bulgaria                   2444.286648
Croatia                    3119.236520
Czech Republic             6876.140250
Denmark                    9692.385245
Finland                    6424.519071
France                     7029.809327
Germany                    7144.114393
Greece                     3530.690067
Hungary                    5263.673816
Iceland                    7267.688428
Ireland                    5210.280328
Italy                      4931.404155
Montenegro                 2647.585601
Netherlands                8941.571858
Norway                    10095.421720
Poland                     4029.329699
Portugal                   3068.319867
Romania                    3144.613186
Serbia                     3581.459448
Slovak Republic            5074.659104
Slovenia                   4215.041741
Spain                      3834.034742
Sweden                     8527.844662
Switzerland               14734.232750
Turkey                     1969.100980
United Kingdom             9979.508487

In [2]:
import os
os.getcwd()

'/Users/zuck016/Desktop'

In [3]:
pwd

'/Users/zuck016/Desktop'

# Data with no country index

In [52]:
data_no_country_idx = pd.read_csv('data/gapminder_gdp_europe.csv')
data_no_country_idx

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
0,Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.003910,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
1,Austria,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.422300,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700
2,Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080
3,Bosnia and Herzegovina,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803
4,Bulgaria,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,7696.777725,10680.792820
5,Croatia,3119.236520,4338.231617,5477.890018,6960.297861,9164.090127,11305.385170,13221.821840,13822.583940,8447.794873,9875.604515,11628.388950,14619.222720
6,Czech Republic,6876.140250,8256.343918,10136.867130,11399.444890,13108.453600,14800.160620,15377.228550,16310.443400,14297.021220,16048.514240,17596.210220,22833.308510
7,Denmark,9692.385245,11099.659350,13583.313510,15937.211230,18866.207210,20422.901500,21688.040480,25116.175810,26406.739850,29804.345670,32166.500060,35278.418740
8,Finland,6424.519071,7545.415386,9371.842561,10921.636260,14358.875900,15605.422830,18533.157610,21141.012230,20647.164990,23723.950200,28204.590570,33207.084400
9,France,7029.809327,8662.834898,10560.485530,12999.917660,16107.191710,18292.635140,20293.897460,22066.442140,24703.796150,25889.784870,28926.032340,30470.016700
10,Germany,7144.114393,10187.826650,12902.462910,14745.625610,18016.180270,20512.921230,22031.532740,24639.185660,26505.303170,27788.884160,30035.801980,32170.374420
11,Greece,3530.690067,4916.299889,6017.190733,8513.097016,12724.829570,14195.524280,15268.420890,16120.528390,17541.496340,18747.698140,22514.254800,27538.411880
12,Hungary,5263.673816,6040.180011,7550.359877,9326.644670,10168.656110,11674.837370,12545.990660,12986.479980,10535.628550,11712.776800,14843.935560,18008.944440
13,Iceland,7267.688428,9244.001412,10350.159060,13319.895680,15798.063620,19654.962470,23269.607500,26923.206280,25144.392010,28061.099660,31163.201960,36180.789190
14,Ireland,5210.280328,5599.077872,6631.597314,7655.568963,9530.772896,11150.981130,12618.321410,13872.866520,17558.815550,24521.947130,34077.049390,40675.996350
15,Italy,4931.404155,6248.656232,8243.582340,10022.401310,12269.273780,14255.984750,16537.483500,19207.234820,22013.644860,24675.024460,27968.098170,28569.719700
16,Montenegro,2647.585601,3682.259903,4649.593785,5907.850937,7778.414017,9595.929905,11222.587620,11732.510170,7003.339037,6465.613349,6557.194282,9253.896111
17,Netherlands,8941.571858,11276.193440,12790.849560,15363.251360,18794.745670,21209.059200,21399.460460,23651.323610,26790.949610,30246.130630,33724.757780,36797.933320
18,Norway,10095.421720,11653.973040,13450.401510,16361.876470,18965.055510,23311.349390,26298.635310,31540.974800,33965.661150,41283.164330,44683.975250,49357.190170
19,Poland,4029.329699,4734.253019,5338.752143,6557.152776,8006.506993,9508.141454,8451.531004,9082.351172,7738.881247,10159.583680,12002.239080,15389.924680
20,Portugal,3068.319867,3774.571743,4727.954889,6361.517993,9022.247417,10172.485720,11753.842910,13039.308760,16207.266630,17641.031560,19970.907870,20509.647770
21,Romania,3144.613186,3943.370225,4734.997586,6470.866545,8011.414402,9356.397240,9605.314053,9696.273295,6598.409903,7346.547557,7885.360081,10808.475610
22,Serbia,3581.459448,4981.090891,6289.629157,7991.707066,10522.067490,12980.669560,15181.092700,15870.878510,9325.068238,7914.320304,7236.075251,9786.534714
23,Slovak Republic,5074.659104,6093.262980,7481.107598,8412.902397,9674.167626,10922.664040,11348.545850,12037.267580,9498.467723,12126.230650,13638.778370,18678.314350
24,Slovenia,4215.041741,5862.276629,7402.303395,9405.489397,12383.486200,15277.030170,17866.721750,18678.534920,14214.716810,17161.107350,20660.019360,25768.257590
25,Spain,3834.034742,4564.802410,5693.843879,7993.512294,10638.751310,13236.921170,13926.169970,15764.983130,18603.064520,20445.298960,24835.471660,28821.063700
26,Sweden,8527.844662,9911.878226,12329.441920,15258.296970,17832.024640,18855.725210,20667.381250,23586.929270,23880.016830,25266.594990,29341.630930,33859.748350
27,Switzerland,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,30281.704590,31871.530300,32135.323010,34480.957710,37506.419070
28,Turkey,1969.100980,2218.754257,2322.869908,2826.356387,3450.696380,4269.122326,4241.356344,5089.043686,5678.348271,6601.429915,6508.085718,8458.276384
29,United Kingdom,9979.508487,11283.177950,12477.177070,14142.850890,15895.116410,17428.748460,18232.424520,21664.787670,22705.092540,26074.531360,29478.999190,33203.261280

In [53]:
data_no_country_idx.loc[0:3, :]

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
0,Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.003910,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
1,Austria,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.422300,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700
2,Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080
3,Bosnia and Herzegovina,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803

# Select-Apply-Combine operations

In [59]:
data <10000

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Albania,True,True,True,True,True,True,True,True,True,True,True,True
Austria,True,True,False,False,False,False,False,False,False,False,False,False
Belgium,True,True,False,False,False,False,False,False,False,False,False,False
Bosnia and Herzegovina,True,True,True,True,True,True,True,True,True,True,True,True
Bulgaria,True,True,True,True,True,True,True,True,True,True,True,False
Croatia,True,True,True,True,True,False,False,False,True,True,False,False
Czech Republic,True,True,False,False,False,False,False,False,False,False,False,False
Denmark,True,False,False,False,False,False,False,False,False,False,False,False
Finland,True,True,True,False,False,False,False,False,False,False,False,False
France,True,True,False,False,False,False,False,False,False,False,False,False
Germany,True,False,False,False,False,False,False,False,False,False,False,False
Greece,True,True,True,True,False,False,False,False,False,False,False,False
Hungary,True,True,True,True,False,False,False,False,False,False,False,False
Iceland,True,True,False,False,False,False,False,False,False,False,False,False
Ireland,True,True,True,True,True,False,False,False,False,False,False,False
Italy,True,True,True,False,False,False,False,False,False,False,False,False
Montenegro,True,True,True,True,True,True,False,False,True,True,True,True
Netherlands,True,False,False,False,False,False,False,False,False,False,False,False
Norway,False,False,False,False,False,False,False,False,False,False,False,False
Poland,True,True,True,True,True,True,True,True,True,False,False,False
Portugal,True,True,True,True,True,False,False,False,False,False,False,False
Romania,True,True,True,True,True,True,True,True,True,True,True,False
Serbia,True,True,True,True,False,False,False,False,True,True,True,True
Slovak Republic,True,True,True,True,True,False,False,False,True,False,False,False
Slovenia,True,True,True,True,False,False,False,False,False,False,False,False
Spain,True,True,True,True,False,False,False,False,False,False,False,False
Sweden,True,True,False,False,False,False,False,False,False,False,False,False
Switzerland,False,False,False,False,False,False,False,False,False,False,False,False
Turkey,True,True,True,True,True,True,True,True,True,True,True,True
United Kingdom,True,False,False,False,False,False,False,False,False,False,False,False

In [58]:
mask = data < 10000
data[mask]

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.003910,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
Austria,6137.076492,8842.598030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Belgium,8343.105127,9714.960623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bosnia and Herzegovina,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803
Bulgaria,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,7696.777725,NaN
Croatia,3119.236520,4338.231617,5477.890018,6960.297861,9164.090127,NaN,NaN,NaN,8447.794873,9875.604515,NaN,NaN
Czech Republic,6876.140250,8256.343918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Denmark,9692.385245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Finland,6424.519071,7545.415386,9371.842561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,7029.809327,8662.834898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Germany,7144.114393,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Greece,3530.690067,4916.299889,6017.190733,8513.097016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hungary,5263.673816,6040.180011,7550.359877,9326.644670,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Iceland,7267.688428,9244.001412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ireland,5210.280328,5599.077872,6631.597314,7655.568963,9530.772896,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Italy,4931.404155,6248.656232,8243.582340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Montenegro,2647.585601,3682.259903,4649.593785,5907.850937,7778.414017,9595.929905,NaN,NaN,7003.339037,6465.613349,6557.194282,9253.896111
Netherlands,8941.571858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Norway,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Poland,4029.329699,4734.253019,5338.752143,6557.152776,8006.506993,9508.141454,8451.531004,9082.351172,7738.881247,NaN,NaN,NaN
Portugal,3068.319867,3774.571743,4727.954889,6361.517993,9022.247417,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Romania,3144.613186,3943.370225,4734.997586,6470.866545,8011.414402,9356.397240,9605.314053,9696.273295,6598.409903,7346.547557,7885.360081,NaN
Serbia,3581.459448,4981.090891,6289.629157,7991.707066,NaN,NaN,NaN,NaN,9325.068238,7914.320304,7236.075251,9786.534714
Slovak Republic,5074.659104,6093.262980,7481.107598,8412.902397,9674.167626,NaN,NaN,NaN,9498.467723,NaN,NaN,NaN
Slovenia,4215.041741,5862.276629,7402.303395,9405.489397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Spain,3834.034742,4564.802410,5693.843879,7993.512294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sweden,8527.844662,9911.878226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Switzerland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Turkey,1969.100980,2218.754257,2322.869908,2826.356387,3450.696380,4269.122326,4241.356344,5089.043686,5678.348271,6601.429915,6508.085718,8458.276384
United Kingdom,9979.508487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN